import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = (props) => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <>
      <Head>
        <title>Sahil Saleem</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>

      <main>
        <h1>Hello World</h1>
      </main>
    </>
  );
};

export default Home;
