import Head from "next/head";
import React, { FC, ReactNode } from "react";
import Header from "./Header";

const Layout: FC<{ children: ReactNode }> = ({ children }) => {
  return (
    <React.Fragment>
      <Head>
        <title>Sahil Saleem</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        {children}
      </main>
    </React.Fragment>
  );
};

export default Layout;
